apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-explorer-data
  namespace: influxdb
  labels:
    app: influxdb-explorer
    app.kubernetes.io/name: influxdb-explorer
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: soil-moisture-probe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
